# Generated by Django 5.1.3 on 2024-11-16 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmer', '0003_farmer_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eartag', models.CharField(max_length=255, unique=True)),
                ('race', models.CharField(max_length=255, null=True)),
                ('gender', models.BooleanField(null=True)),
                ('room', models.CharField(max_length=255)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('feed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='Farmer.company')),
            ],
        ),
    ]
