# Generated by Django 5.1.3 on 2024-12-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='is_deleted',
            new_name='is_slaughtered',
        ),
    ]
