# Generated by Django 5.1.3 on 2024-12-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0002_rename_is_deleted_animal_is_slaughtered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_groups', to='Animal.animal')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_groups', to='Animal.group')),
            ],
            options={
                'unique_together': {('animal', 'group')},
            },
        ),
    ]
