# Generated by Django 5.1.3 on 2025-01-06 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0003_group_animalgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='dry_matter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
