# Generated by Django 4.2.21 on 2025-05-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0004_group_created_at_group_dry_matter_group_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='updated_at',
        ),
    ]
