# Generated by Django 5.1.3 on 2024-11-18 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Animal', '0002_animal_created_at_animal_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('recorded_at', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='Animal.animal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('animal', 'recorded_at'), name='unique_weight_per_month')],
            },
        ),
    ]
