# Generated by Django 5.1.3 on 2024-12-18 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='recorded_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
