# Generated by Django 5.1.3 on 2024-12-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RationTableComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration_components.rationcomponent')),
                ('ration_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration_components.rationtable')),
            ],
            options={
                'unique_together': {('ration_table', 'component')},
            },
        ),
        migrations.AddField(
            model_name='rationtable',
            name='components',
            field=models.ManyToManyField(through='ration_components.RationTableComponent', to='ration_components.rationcomponent'),
        ),
        migrations.CreateModel(
            name='RationComponentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ration_table_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration_components.rationtablecomponent')),
            ],
        ),
    ]
