# Generated by Django 5.1.3 on 2024-12-21 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationcomponentchange',
            name='ration_table_component',
        ),
        migrations.AddField(
            model_name='rationcomponentchange',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], default='UPDATED', max_length=10),
        ),
        migrations.AddField(
            model_name='rationcomponentchange',
            name='component_name',
            field=models.CharField(default='Unknown Component', max_length=255),
        ),
        migrations.AddField(
            model_name='rationcomponentchange',
            name='ration_table_component_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='rationcomponentchange',
            name='ration_table_name',
            field=models.CharField(default='Unknown Ration Table', max_length=255),
        ),
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='new_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='old_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rationtablecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ration_components.rationcomponent'),
        ),
    ]
