# Generated by Django 5.1.3 on 2024-12-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0002_remove_rationcomponentchange_ration_table_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='component_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='new_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='old_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='ration_table_component_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='ration_table_name',
            field=models.CharField(max_length=255),
        ),
    ]
