# Generated by Django 5.1.3 on 2024-12-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0003_alter_rationcomponentchange_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcomponent',
            name='dry_matter',
            field=models.DecimalField(decimal_places=2, default=0.88, help_text='Dry matter percentage of the component', max_digits=5),
            preserve_default=False,
        ),
    ]
