# Generated by Django 5.1.3 on 2024-12-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0004_rationcomponent_dry_matter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcomponent',
            name='calori',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rationcomponent',
            name='nisasta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rationcomponent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
