# Generated by Django 5.1.3 on 2024-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0006_rationcomponentchange_new_calori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationcomponentchange',
            name='ration_table_component_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
