# Generated by Django 5.1.3 on 2024-12-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0008_auto_20241228_0808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RationComponentChange',
        ),
    ]
