# Generated by Django 5.1.3 on 2024-12-29 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0010_alter_rationtablecomponent_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationtablecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ration_components.rationcomponent'),
        ),
    ]
