# Generated by Django 5.1.3 on 2024-12-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0011_alter_rationtablecomponent_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcomponent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
