# Generated by Django 5.1.3 on 2024-12-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0012_rationcomponent_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationtable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rationtablecomponent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rationcomponent',
            name='dry_matter',
            field=models.DecimalField(decimal_places=2, help_text='Dry matter percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='rationcomponent',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
