# Generated by Django 5.1.3 on 2024-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0013_rationtable_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationcomponent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
