# Generated by Django 5.1.3 on 2025-01-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0014_rationcomponent_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationtablecomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ration_components.rationcomponent'),
        ),
    ]
