# Generated by Django 5.1.3 on 2025-01-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_components', '0015_alter_rationtablecomponent_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationtable',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rationtablecomponent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
