# Generated by Django 5.1.3 on 2025-01-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentchangelog',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='componentchangelog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentchangelog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
