# Generated by Django 5.1.3 on 2024-12-17 20:22

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+90000000000', max_length=128, region='TR'),
        ),
    ]
