# Generated by Django 5.1.3 on 2024-11-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0002_farmer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
