# Generated by Django 5.1.3 on 2024-12-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_farmer_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='age',
        ),
        migrations.AddField(
            model_name='farmer',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
