# Generated by Django 5.1.3 on 2024-12-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Animal', '0003_group_animalgroup'),
        ('ration_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ration_logs', to='Animal.animal')),
                ('ration_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_logs', to='ration_components.rationtable')),
            ],
        ),
    ]
