# Generated by Django 5.1.3 on 2024-12-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slaughter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('carcas_weight', models.FloatField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kdv', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slaughters', to='Animal.animal')),
            ],
        ),
    ]
