# Generated by Django 5.1.3 on 2024-12-20 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaughter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughter',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slaughter',
            name='kdv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slaughter',
            name='sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
