# Generated by Django 5.1.3 on 2024-12-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaughter', '0002_alter_slaughter_date_alter_slaughter_kdv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughter',
            name='kdv',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='slaughter',
            name='sale_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
