# Generated by Django 5.1.3 on 2024-12-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaughter', '0003_alter_slaughter_kdv_alter_slaughter_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughter',
            name='sale_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
