# Generated by Django 5.1.3 on 2024-12-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaughter', '0004_alter_slaughter_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughter',
            name='carcas_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
