# Generated by Django 5.1.3 on 2024-12-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaughter', '0005_alter_slaughter_carcas_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughter',
            name='carcas_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='slaughter',
            name='sale_price',
            field=models.FloatField(default=0.0),
        ),
    ]
