# Generated by Django 5.1.3 on 2024-12-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slaughter', '0002_slaughter_kdv'),
        ('Slaughter', '0006_alter_slaughter_carcas_weight_and_more'),
    ]

    operations = [
    ]
