# Generated by Django 5.1.3 on 2024-12-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slaughter', '0007_merge_20241221_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughter',
            name='kdv',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
